In [6]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA


df = pd.read_csv("newBAF_standardized.csv")
df = df.drop(columns = 'Unnamed: 0')

In [7]:
df.head(10)

,sku,Dept_800,Dept_801,Dept_1100,Dept_1107,Dept_1202,Dept_1301,Dept_1704,Dept_1905,Dept_2102,...,EastNorthCentral,EastSouthCentral,Mountain,Pacific,SouthAtlantic,WestNorthCentral,WestSouthCentral,Percent.Discount,Percentage.Return,log_avg
0,8909301,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0.000000,0.000000,0.656564
1,8911368,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0.611111,0.111111,0.484947
2,8911651,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0.729000,0.052632,0.256005
3,8912722,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0.503500,0.029801,0.226126
4,8913028,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0.670975,0.125000,0.328250
5,8917543,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0.396631,0.054422,0.586422
6,8919343,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0.000000,0.000000,0.728068
7,8923761,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0.319796,0.125000,0.610452
8,8927709,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0.520313,0.162791,0.470367
9,8928303,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0.585714,0.142857,0.390015

In [15]:
import numpy as np
from sklearn.mixture import GaussianMixture
GMM = GaussianMixture(n_components = 7, random_state=0).fit(df.loc[:, df.columns != 'sku']) #7 chosen by pca and kmeans

In [18]:
p = GMM.predict(df.loc[:, df.columns != 'sku'])
df["labels"] = p

In [19]:
df.head(10)

,sku,Dept_800,Dept_801,Dept_1100,Dept_1107,Dept_1202,Dept_1301,Dept_1704,Dept_1905,Dept_2102,...,EastSouthCentral,Mountain,Pacific,SouthAtlantic,WestNorthCentral,WestSouthCentral,Percent.Discount,Percentage.Return,log_avg,labels
0,8909301,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0.000000,0.000000,0.656564,0
1,8911368,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0.611111,0.111111,0.484947,1
2,8911651,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0.729000,0.052632,0.256005,3
3,8912722,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0.503500,0.029801,0.226126,1
4,8913028,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0.670975,0.125000,0.328250,2
5,8917543,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0.396631,0.054422,0.586422,2
6,8919343,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0.000000,0.000000,0.728068,0
7,8923761,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0.319796,0.125000,0.610452,2
8,8927709,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0.520313,0.162791,0.470367,0
9,8928303,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0.585714,0.142857,0.390015,6

In [20]:
sku_label_df = df[["sku", "labels"]]
sku_label_df.head(10)

       sku  labels
0  8909301       0
1  8911368       1
2  8911651       3
3  8912722       1
4  8913028       2
5  8917543       2
6  8919343       0
7  8923761       2
8  8927709       0
9  8928303       6

In [22]:
sku_label_df.to_csv('gmm_labels.csv', index = False)